server:
  port: 8082

spring:
  application:
    name: payment-service

  config:
    import: optional:file:../.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/upimesh_ledger
    username: payment_svc
    password: ${PAYMENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Flyway database migrations MUST be true to create your tables
  flyway:
    enabled: true
    baseline-on-migrate: true

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: validate # Flyway handles schema generation
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always